[package]
name = "non-uniform-rational-b-spline-regression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
charts = "0.3.0"
float-cmp = "0.9.0"
rand = "0.8.5"
